"""TigerGraph graph schema for fraud detection.

The schema is intentionally narrow but expressive. It models the four most
common fraud-amplifying pivots in retail banking:

- ``Customer`` — the human behind one or more ``Account`` rows
- ``Account`` — checking / credit / savings account
- ``Card`` — payment card bound to an account
- ``Device`` — phone / laptop / POS terminal fingerprint
- ``IP`` — login IP address
- ``Merchant`` — counter-party in a transaction
- ``Transaction`` — money movement event

Edges encode *how* these are connected. Several edges (``SHARES_DEVICE``,
``SHARES_IP``) are computed post-load by the detection layer, but we
pre-declare them so the schema is self-documenting.
"""

from __future__ import annotations

VERTEX_TYPES: dict[str, str] = {
    "Customer": """
        CREATE VERTEX Customer (
            PRIMARY_ID id STRING,
            name STRING,
            dob STRING,
            country STRING,
            risk_score DOUBLE
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "Account": """
        CREATE VERTEX Account (
            PRIMARY_ID id STRING,
            account_type STRING,
            opened_at STRING,
            balance DOUBLE,
            status STRING,
            risk_score DOUBLE
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "Card": """
        CREATE VERTEX Card (
            PRIMARY_ID id STRING,
            card_type STRING,
            brand STRING,
            issued_at STRING,
            status STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "Device": """
        CREATE VERTEX Device (
            PRIMARY_ID id STRING,
            fingerprint STRING,
            device_type STRING,
            os STRING,
            first_seen STRING,
            last_seen STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "IP": """
        CREATE VERTEX IP (
            PRIMARY_ID id STRING,
            asn STRING,
            country STRING,
            city STRING,
            reputation DOUBLE
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "Merchant": """
        CREATE VERTEX Merchant (
            PRIMARY_ID id STRING,
            name STRING,
            mcc STRING,
            country STRING,
            risk_score DOUBLE
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "Transaction": """
        CREATE VERTEX Transaction (
            PRIMARY_ID id STRING,
            ts STRING,
            amount DOUBLE,
            currency STRING,
            channel STRING,
            status STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
}


EDGE_TYPES: dict[str, str] = {
    "OWNS": """
        CREATE DIRECTED EDGE OWNS (
            FROM Customer, TO Account,
            since STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "HAS_CARD": """
        CREATE DIRECTED EDGE HAS_CARD (
            FROM Account, TO Card,
            since STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "USES_DEVICE": """
        CREATE DIRECTED EDGE USES_DEVICE (
            FROM Account, TO Device,
            first_seen STRING,
            last_seen STRING,
            count INT
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "LOGGED_FROM": """
        CREATE DIRECTED EDGE LOGGED_FROM (
            FROM Account, TO IP,
            first_seen STRING,
            last_seen STRING,
            count INT
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "PAID_TO": """
        CREATE DIRECTED EDGE PAID_TO (
            FROM Transaction, TO Merchant,
            amount DOUBLE
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "FROM_ACCOUNT": """
        CREATE DIRECTED EDGE FROM_ACCOUNT (
            FROM Transaction, TO Account,
            amount DOUBLE,
            ts STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "TO_ACCOUNT": """
        CREATE DIRECTED EDGE TO_ACCOUNT (
            FROM Transaction, TO Account,
            amount DOUBLE,
            ts STRING
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "SHARES_DEVICE": """
        CREATE UNDIRECTED EDGE SHARES_DEVICE (
            FROM Account, TO Account,
            device_id STRING,
            count INT
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
    "SHARES_IP": """
        CREATE UNDIRECTED EDGE SHARES_IP (
            FROM Account, TO Account,
            ip_id STRING,
            count INT
        ) WITH STATS = "OUTDEGREE_BY_EDGETYPE"
    """,
}


def _strip(text: str) -> str:
    return "\n".join(line.rstrip() for line in text.strip().splitlines())


GSQL_SCHEMA: str = (
    "-- Auto-generated by fraud_risk_engine.schema.graph_schema\n"
    "CREATE GRAPH FraudRisk(*)\n\n"
    + "\n\n".join(_strip(ddl) for ddl in VERTEX_TYPES.values())
    + "\n\n"
    + "\n\n".join(_strip(ddl) for ddl in EDGE_TYPES.values())
    + "\n"
)